### ISSUE TITLE
Default Calendar Display and Details to Next Upcoming Event

### ISSUE THREAD

**Issue by timsavery** [NodePhilly/nodeph-website#11]

**Comment by keithelliott** [comment]
This issue is fixed.  Now when you navigate to new month, the event shows up in the feature without having to click on it.

**Comment by timsavery** [comment]
Awesome.  When the home page loads does it go right to the aug 23rd event?

**Comment by keithelliott** [comment]
Yes, I will probably need to add a check for multiple events being created on a day or month.  I wasn't sure how you were creating events.  So, it works for sure when there is only one event on the calendar.  I will look into fixing it for multiple events in a month today.

**Comment by keithelliott** [comment]
Broke out the function to do this work and check that it adds just the first event from the calendar
