### ISSUE TITLE
Months that Span Six Weeks Can't Display Last Week

### ISSUE THREAD

**Issue by timsavery** [NodePhilly/nodeph-website#12]
Add sixth week to calendar.

Can we:
1) shrink cells?
2) shrink node.js footer and expand calendar?

**Comment by timsavery** [comment]
Example: September 2012

**Comment by brettnotbrent** [comment]
Sending an email detailing this issue since there's no image attachment here yet.

**Comment by timsavery** [comment]
deployed. fix looks good.
