### ISSUE TITLE
Missing 2012 (year) in Footer

### ISSUE THREAD

**Issue by timsavery** [NodePhilly/nodeph-website#17]

**Comment by bsaroukos** [comment]
Brett, is this done?

**Comment by brettnotbrent** [comment]
yea should be. i thought i closed it sorry. 

–––––––––––––––––––––––––––––
Brett Whitham
Art Direction, Design, Creative Consulting

Twitter: @bwhitham
302.682.1330

**Comment by bsaroukos** [comment]
I don't have permission to close it.  Can you take care of it?
