### ISSUE TITLE
Get the PTW2013 page to accept payments

### ISSUE THREAD

**Issue by brettnotbrent** [NodePhilly/nodeph-website#36]
We'd like to have the ability for users to directly submit a sponsorship payment through the website.

**Comment by wilwang** [comment]
still needs
1) stylization
2) setup official nodephilly stripe account
3) deployment with stripe environment variables set
4) some testing

**Comment by timsavery** [comment]
we will use their secure popup for the sponsorship payments...we can turn our sponsorship guide into a page (maybe a section on the event page?

**Comment by timsavery** [comment]
we will use stripe checkout: https://stripe.com/docs/checkout

**Comment by timsavery** [comment]
/sponsorship now has each of our sponsorships, not accesible directly from the ptw2013 site, but should point sponsors to https://node.ph/sponsorship for payment.
