### ISSUE TITLE
TicketLeap API or Widget

### ISSUE THREAD

**Issue by brettnotbrent** [NodePhilly/nodeph-website#37]
Get a Ticketleap widget working on the PTW2013 page. Towards the bottom of the shell page should be a space for tickets. For now, just a text link will be ok that brings up an in-app popup with the ticket module in it.

**Comment by timsavery** [comment]
They do not have a pre-built widget for ticket ordering like EventBrite has. Hooked up the current link to launch a new tab with our ticket page loaded. Fixed with e0bd5f9c7e9e863acee497971ecd2e6771d4023a
