### ISSUE TITLE
Investigate publishing articles/entries

### ISSUE THREAD

**Issue by brettnotbrent** [NodePhilly/nodeph-website#40]
How can we get the site set up to allow us to easily publish articles and information that will be useful for our users?

**Comment by wilwang** [comment]
Is this something I can help with?

**Comment by brettnotbrent** [comment]
Yea, definitely. If you'd like to look into some ways we could start to easily publish, display, and organize article/blog entries, that'd be fantastic.

**Comment by timsavery** [comment]
I already started an implementation of a blog using Jordan's poet.js module...I think that stuff is still in master. hell...it may almost be done for all I remember.
