### ISSUE TITLE
PTW2013 - Build a redirect for mobile devices

### ISSUE THREAD

**Issue by brettnotbrent** [NodePhilly/nodeph-website#42]
Create a check to see if a user is on a mobile phone (iPhone, Droid, etc) and redirect them to a mobile site for our PTW2013 event page. "m.node.ph/ptw2013" maybe? Thoughts on the URL?

This may make it easier for us versus having a media query to handle the page adjustments since this event page is image-heavy.

**Comment by bryanpaluch** [comment]
+1, but the domain mobile trick is difficult to handle in an express app, you may want to just redirect to /m/normalroutes  , and use different templates. This way you don't have to run a separate app.

**Comment by timsavery** [comment]
seems like this could work...separate apps, but hosted in same process: http://stackoverflow.com/questions/5791260/how-can-i-configure-multiple-sub-domains-in-express-js-or-connect-js

...or just host a separate app on Nodejitsu :)

**Comment by brettnotbrent** [comment]
Sounds good to me.

Let me know if this is totally unreasonable and I'll try to hack something up for a media query tomorrow. Most of the site is done and we should be good to launch w/in two days. It'd be awesome if this released w/it or followed shortly after.
