### ISSUE TITLE
Create Gallery Page

### ISSUE THREAD

**Issue by keithelliott** [NodePhilly/nodeph-website#5]
I created an instagram account for nodephilly.  I also requested a developer's key for our app.  Once we get that back, we can work on adding this to the site in the gallery section

**Comment by timsavery** [comment]
@keithelliott forgot to put the '@' sign in front of the 'nodephilly' for the instagram link.  @bwhitham fixed it up for you already.

**Comment by timsavery** [comment]
This will populate the "Gallery" page.
