### ISSUE TITLE
Get stripe working for Hack and Hops

### ISSUE THREAD

**Issue by brettnotbrent** [NodePhilly/nodeph-website#51]
Sponsors need a way to give us money to pay for our billz.

**Comment by brettnotbrent** [comment]
@timsavery should know a bit about this if you need some help.

**Comment by timsavery** [comment]
is this done?

**Comment by wilwang** [comment]
Assuming back end is working. I was just gonna put in a drop down so we can
test the 1$ charge. Code is local right now

Sent from my iPhone

On Oct 18, 2013, at 8:28 PM, Tim Savery notifications@github.com wrote:

is this done?

—
Reply to this email directly or view it on
GitHubhttps://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26639255
.

**Comment by timsavery** [comment]
cool.  Let me know what you need from me. we will need sponsors to pay soon :)

**Comment by wilwang** [comment]
Will let commit something today probably. I'll email u so u can deploy it

Sent from my iPhone

On Oct 18, 2013, at 8:30 PM, Tim Savery notifications@github.com wrote:

cool. Let me know what you need from me. we will need sponsors to pay soon
:)

On Oct 18, 2013, at 8:29 PM, Wil Wang notifications@github.com wrote:

> Assuming back end is working. I was just gonna put in a drop down so we
> can
> test the 1$ charge. Code is local right now
> 
> Sent from my iPhone
> 
> On Oct 18, 2013, at 8:28 PM, Tim Savery notifications@github.com wrote:
> 
> is this done?
> 
> —
> Reply to this email directly or view it on
> GitHub<
> https://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26639255>
> 
> .
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on
GitHubhttps://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26639310
.

**Comment by timsavery** [comment]
word

**Comment by wilwang** [comment]
Updated sponsorship to use a drop down for sponsorship amounts - a $1.00
amount is available for testing use.

fyi, looks like the geeklist and twitter stuff was taken out of the app.js.
 Was that on purpose?

**Comment by timsavery** [comment]
I think Ted took that out

-- Tim

**Comment by tstrohecker** [comment]
I had taken it out because I didn't have creds for it and I needed to throw
together some stuff for Brett, it probably should go back in. I blame Brett
for not giving me the creds.

**Comment by timsavery** [comment]
I vote Brett off the island

-- Tim

**Comment by wilwang** [comment]
too late - he already voted you off for missing the hack and hops talk  ;)

**Comment by timsavery** [comment]
He may win this battle, the war is still up for grabs.

-- Tim

**Comment by brettnotbrent** [comment]
Yes, Will is correct. You lost voting privileges when you bailed on Hack
and Hops. And I gave Ted the creds but apparently his level of "software
engineer" isn't high enough for him to know how to copy and paste into the
command line. And I learned a new term… code smell. Ted, your command line
is code smelly.

On Fri, Oct 18, 2013 at 11:28 PM, Tim Savery notifications@github.comwrote:

> He may win this battle, the war is still up for grabs.
> 
> -- Tim
> 
> On Fri, Oct 18, 2013 at 11:23 PM, Wil Wang notifications@github.com
> wrote:
> 
> > too late - he already voted you off for missing the hack and hops talk
> > ;)
> > On Fri, Oct 18, 2013 at 11:22 PM, Tim Savery notifications@github.comwrote:
> > 
> > > I vote Brett off the island
> > > 
> > > -- Tim
> > > 
> > > On Fri, Oct 18, 2013 at 11:20 PM, tstrohecker notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > I had taken it out because I didn't have creds for it and I needed to
> > > > throw
> > > > together some stuff for Brett, it probably should go back in. I blame
> > > > Brett
> > > > for not giving me the creds.
> > > > On Oct 18, 2013 11:08 PM, "Wil Wang" notifications@github.com
> > > > wrote:
> > > > 
> > > > > Updated sponsorship to use a drop down for sponsorship amounts - a
> > > > > $1.00
> > > > > amount is available for testing use.
> > > > > 
> > > > > fyi, looks like the geeklist and twitter stuff was taken out of the
> > > > > app.js.
> > > > > Was that on purpose?
> > > > > 
> > > > > On Fri, Oct 18, 2013 at 8:31 PM, Tim Savery <
> > > > > notifications@github.com>wrote:
> > > > > 
> > > > > > word
> > > > > > On Oct 18, 2013, at 8:31 PM, Wil Wang notifications@github.com
> > > > > > wrote:
> > > > > > 
> > > > > > > Will let commit something today probably. I'll email u so u can
> > > > > > > deploy
> > > > > > > it
> > > > > > > 
> > > > > > > Sent from my iPhone
> > > > > > > 
> > > > > > > On Oct 18, 2013, at 8:30 PM, Tim Savery <
> > > > > > > notifications@github.com>
> > > > > > > wrote:
> > > > > > > 
> > > > > > > cool. Let me know what you need from me. we will need sponsors
> > > > > > > to
> > > > > > > pay
> > > > > > > soon
> > > > > > > :)
> > > > > > > 
> > > > > > > On Oct 18, 2013, at 8:29 PM, Wil Wang notifications@github.com
> > > > > 
> > > > > wrote:
> > > > > 
> > > > > > > > Assuming back end is working. I was just gonna put in a drop
> > > > > > > > down
> > > > > > > > so
> > > > > > > > we
> > > > > > > > can
> > > > > > > > test the 1$ charge. Code is local right now
> > > > > > > > 
> > > > > > > > Sent from my iPhone
> > > > > > > > 
> > > > > > > > On Oct 18, 2013, at 8:28 PM, Tim Savery <
> > > > > > > > notifications@github.com>
> > > > > > 
> > > > > > wrote:
> > > > > > 
> > > > > > > > is this done?
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on
> > > > > > > > GitHub<
> > > 
> > > https://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26639255>
> > > 
> > > > > > > > .
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub.
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on
> > > > > > > GitHub<
> > > 
> > > https://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26639310>
> > > 
> > > > > > > .
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26639349>
> > > 
> > > > > > .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26642188>
> > > 
> > > > > .
> > > > > 
> > > > > ---
> > > > > 
> > > > > Reply to this email directly or view it on GitHub:
> > > 
> > > https://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26642357
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26642382>
> > > 
> > > .
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26642399
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NodePhilly/nodeph-website/issues/51#issuecomment-26642483
> .

## 

---

## *Brett Whitham \* |  @bwhitham http://www.twitter.com/bwhitham

UX Lead @ChathamFin http://www.twitter.com/chathamfin
Org @NodePhilly http://www.twitter.com/nodephilly

## Freelance @ humenic.com

1.302.682.1330

**Comment by tstrohecker** [comment]
Yeah I've been known to have bad command line code smell.

**Comment by wilwang** [comment]
i've added back the twitter and geeklist stuff in app.js - just need a
deploy
