### ISSUE TITLE
Create Events Page

### ISSUE THREAD

**Issue by timsavery** [NodePhilly/nodeph-website#9]
Populate with data from shared calendar.  Should include bookmark functionality to go to specified event.

**Comment by timsavery** [comment]
assigning to @bwhitham for layout design, then someone else to fill in.

**Comment by timsavery** [comment]
working on this one now.

**Comment by timsavery** [comment]
@bwhitham you got a design for this yet?  I want to get this up and out so we can post agenda and speaker bios.

**Comment by brettnotbrent** [comment]
the layout for this has been committed. just need to have real data fed into it. can be found at "…/events"
